(function(){
const ready=()=>{if(!document.body||!document.getElementById('desktop'))return;
const html='<div id="firstRun" class="hidden" role="dialog" aria-modal="true" aria-labelledby="setupTitle"><section class="setup-card"><div class="setup-mark">AWEONE · SYSTEM INITIALIZATION</div><h1 id="setupTitle">Welcome to AWEWEBOS</h1><p class="muted">Set up your workspace before using the desktop.</p><div class="setup-grid"><div><label for="setupLanguage">Language preference</label><select id="setupLanguage" class="field"><option value="hy">Հայերեն — Armenian</option><option value="en">English</option><option value="ru">Русский — Russian</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="es">Español</option><option value="ar">العربية</option><option value="zh-CN">中文</option><option value="fa">فارسی</option><option value="ka">ქართული</option></select></div><div><label for="setupKeyboard">Keyboard preference</label><select id="setupKeyboard" class="field"><option value="hy">Armenian</option><option value="en-US">English (US)</option><option value="en-GB">English (UK)</option><option value="ru">Russian</option><option value="fr">French (AZERTY)</option><option value="de">German (QWERTZ)</option><option value="es">Spanish</option><option value="other">System default</option></select></div></div><label for="setupTheme">Desktop theme</label><select id="setupTheme" class="field"><option value="aurora">Aurora Dark</option><option value="light">Light</option><option value="midnight">Midnight Blue</option><option value="contrast">High Contrast</option></select><div class="card"><h3>Workspace folder / disk</h3><p class="small muted">Choose a folder to store and manage files, where supported.</p><div class="row"><button id="setupChooseFolder">📁 Choose folder</button><span id="setupFolderStatus" class="small muted">Not selected</span></div></div><div class="setup-note">A website/PWA cannot choose its own installation directory or change the operating-system keyboard layout. Native installers use each platform's installation flow. This wizard saves preferences and a workspace folder.</div><button id="setupFinish" class="primary" style="width:100%;padding:13px;margin-top:8px">Finish setup and open desktop →</button><p class="small muted">You can reopen setup from Settings.</p></section></div>';
document.body.insertAdjacentHTML('beforeend',html);
const el=id=>document.getElementById(id);
window.showSetup=function(){el('firstRun').classList.remove('hidden');el('setupLanguage').value=(window.data&&data.language)||'hy';el('setupKeyboard').value=(window.data&&data.keyboard)||'hy';el('setupTheme').value=(window.data&&data.theme)||'aurora';el('setupFolderStatus').textContent=window.folder?'Selected: '+folder.name:((window.data&&data.workspaceName)||'Not selected')};
window.finishSetup=function(){data.language=el('setupLanguage').value;data.keyboard=el('setupKeyboard').value;data.theme=el('setupTheme').value;save();localStorage.setItem('awewebos.setup.complete','1');document.documentElement.lang=data.language;applyTheme();el('firstRun').classList.add('hidden');toast('Setup saved. Welcome to AWEWEBOS.')};
window.applyTheme=function(){const t=(window.data&&data.theme)||'aurora';const root=document.documentElement;if(t==='light'){root.style.setProperty('--bg','#eef3fa');root.style.setProperty('--panel','#fff');root.style.setProperty('--line','#c5d2e2');root.style.setProperty('--text','#17263c');root.style.setProperty('--muted','#53677f');document.body.style.background='#eef3fa';document.body.style.color='#17263c'}else if(t==='contrast'){root.style.setProperty('--bg','#000');root.style.setProperty('--panel','#000');root.style.setProperty('--line','#fff');root.style.setProperty('--text','#fff');root.style.setProperty('--muted','#fff');document.body.style.background='#000';document.body.style.color='#fff'}else{root.style.setProperty('--bg','#080d18');root.style.setProperty('--panel',t==='midnight'?'#0b1024':'#101c30');root.style.setProperty('--line','#2a3d59');root.style.setProperty('--text','#e9f2ff');root.style.setProperty('--muted','#9aabc4');document.body.style.background='radial-gradient(ellipse at 75% 20%,#18365c,transparent 38%),radial-gradient(ellipse at 20% 85%,#112c45,transparent 42%),#080d18';document.body.style.color='var(--text)'}};
el('setupChooseFolder').addEventListener('click',async()=>{if(!window.showDirectoryPicker){toast('Folder picker needs a supported Chromium browser');return}try{const h=await window.showDirectoryPicker({mode:'readwrite'});if(await h.requestPermission({mode:'readwrite'})!=='granted'){toast('Folder permission was not granted');return}window.folder=h;await saveSharedFolderHandle(h);data.workspaceName=h.name;save();el('setupFolderStatus').textContent='Selected: '+h.name;toast('Workspace folder connected')}catch(e){if(e.name!=='AbortError')toast('Could not select folder')}});
el('setupFinish').addEventListener('click',window.finishSetup);
window.hideContextMenu=function(){el('aweContextMenu')?.remove()};
document.addEventListener('contextmenu',e=>{if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;e.preventDefault();hideContextMenu();const menu=document.createElement('div');menu.id='aweContextMenu';menu.className='context-menu';menu.style.left=Math.min(e.clientX,innerWidth-230)+'px';menu.style.top=Math.min(e.clientY,innerHeight-310)+'px';menu.innerHTML='<button data-app="files">📁 &nbsp; Files & workspace</button><button data-app="browser">🧭 &nbsp; AWE Browser</button><button data-app="messenger">💬 &nbsp; AWE Messenger</button><button data-app="store">🛍️ &nbsp; AWESTORE</button><hr><button data-app="settings">⚙️ &nbsp; System settings</button><button data-setup="1">✨ &nbsp; Setup wizard</button><button data-install="1">⬇️ &nbsp; Install AWEWEBOS</button><hr><button data-refresh="1">↻ &nbsp; Refresh desktop</button>';document.body.appendChild(menu);menu.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.app)openApp(b.dataset.app);if(b.dataset.setup)showSetup();if(b.dataset.install)installPWA();if(b.dataset.refresh)location.reload();hideContextMenu()});setTimeout(()=>document.addEventListener('pointerdown',outside,{once:true}),0)});
function outside(e){if(!e.target.closest('#aweContextMenu'))hideContextMenu()}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.code==='Space'){e.preventDefault();launcher()}if(e.key==='Escape')hideContextMenu()});
if(!localStorage.getItem('awewebos.setup.complete'))showSetup();else{el('firstRun').classList.add('hidden');if(data.language)document.documentElement.lang=data.language}applyTheme();
};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();